name: DummyApp
options:
  bundleIdPrefix: com.my.dummy.app
targets:
  DummyApp:
    type: application
    platform: iOS
    deploymentTarget: "13.4"
    sources: [DummyApp]
    configFiles:
      Debug: xcconfig/DummyApp.debug.xcconfig
      Release: xcconfig/DummyApp.release.xcconfig
